<?php

namespace ByJG\Serialize;
use Tests\Sample\ModelPublic;
use Tests\Sample\SampleModel;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-10 at 09:36:37.
 */
class BinderObjectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers ByJG\Serialize\BinderObject::bind
     */
    public function testBind_Constructor()
    {
        $object1 = new SampleModel( ['Id' => 10, 'Name' => 'Joao']);
        $this->assertEquals(10, $object1->Id);
        $this->assertEquals('Joao', $object1->getName());
    }

    /**
     * @covers ByJG\Serialize\BinderObject::bind
     */
    public function testBind_Array()
    {
        $object1 = new SampleModel();
        $object1->bind( ['Id' => 10, 'Name' => 'Joao'] );
        $this->assertEquals(10, $object1->Id);
        $this->assertEquals('Joao', $object1->getName());
    }

    /**
     * @covers ByJG\Serialize\BinderObject::bind
     */
    public function testBind_StdClass()
    {
        $stdClass = new \stdClass();
        $stdClass->Id = 10;
        $stdClass->Name = 'Joao';

        $object1 = new SampleModel();
        $object1->bind( $stdClass );
        $this->assertEquals(10, $object1->Id);
        $this->assertEquals('Joao', $object1->getName());
    }

    /**
     * @covers ByJG\Serialize\BinderObject::bindTo
     */
    public function testBindTo_Object()
    {
        $object1 = new SampleModel();
        $object1->Id = 10;
        $object1->setName('Joao');

        $object2 = new SampleModel();
        $object1->bindTo($object2);

        $this->assertEquals(10, $object2->Id);
        $this->assertEquals('Joao', $object2->getName());
    }

    /**
     * @covers ByJG\Serialize\BinderObject::bindTo
     * @todo   Implement testBindTo().
     */
    public function testBindTo_stdClass()
    {
        $object1 = new SampleModel();
        $object1->Id = 10;
        $object1->setName('Joao');

        $object2 = new \stdClass();
        $object1->bindTo($object2);

        $this->assertEquals(10, $object2->Id);
        $this->assertEquals('Joao', $object2->Name);
    }

    /**
     * @covers ByJG\Serialize\BinderObject::toArray
     */
    public function testToArray()
    {
        $object1 = new SampleModel();
        $object1->Id = 10;
        $object1->setName('Joao');

        $object2 = $object1->toArray();

        $this->assertEquals(10, $object2['Id']);
        $this->assertEquals('Joao', $object2['Name']);
    }

    public function testComplexBind()
    {
        $model = new ModelPublic(20, 'JG');

        $data = new \stdClass();
        $data->Id = 10;
        $data->Name = $model;

        $object = new SampleModel($data);

        $this->assertEquals(10, $object->Id);
        $this->assertEquals($model, $object->getName());
    }

}
